### ISSUE TITLE
Exception about nvoglv64 in OnPaint()

### ISSUE THREAD

**Issue by Asubayo** [usingcpp/wxVulkanTutorial#1]
Hi,
I am interested in your example of vulkan with wxwidget. 
But by running your program, I meet the following exception : 

> "Exception thrown at 0x000000005C363844 (nvoglv64.dll) in Application.exe: 0xC0000005: Access violation reading location 0x0000000000000058."

It happens on _"result = vkQueueSubmit(m_graphicsQueue, 1, &submitInfo, VK_NULL_HANDLE); "_ in the OnPaint function. Do you know what could be wrong ?

Thank you,

**Comment by usingcpp** [comment]
I have updated two methods in VulkanCanvas (CreateSubmitInfo and CreatePresentInfoKHR) that were causing problems. I also changed the code so that Vulkan validation is turned on in debug mode.

**Comment by usingcpp** [comment]
I am closing this issue now. If you are still having problems, then either reopen this issue (if this is possible), or open a new one.
